language: node_js

node_js:
  - "8"
  - "10"

install:
  - npm install

  script:
  - npm run test:coverage

after_script:
  - npm install coveralls && cat ./coverage/report-lcov/lcov.info | ./node_modules/.bin/coveralls

notifications:
  email: false
